import { ChannelType, PermissionFlagsBits } from 'discord.js';

export const BRAND = {
  name: 'EMUPLCOOM',
  color: 0x21d4fd,
  accentColor: 0x9b5cff,
  footer: 'EMUPLCOOM • społeczność emulatorów / emulator community',
};

export const VERIFICATION_ROLE_ID = '1476867174390825102';

export const ROLE_KEYS = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  SUPPORT: 'SUPPORT',
  CREATOR: 'CREATOR',
  TESTER: 'TESTER',
  VIP: 'VIP',
  UNVERIFIED: 'UNVERIFIED',
  MEMBER: 'MEMBER',
  VERIFIED: 'VERIFIED',
  POLISH: 'POLISH',
  ENGLISH: 'ENGLISH',
  NEWS: 'NEWS',
  EVENTS: 'EVENTS',
  GAMING: 'GAMING',
  PC: 'PC',
  ANDROID: 'ANDROID',
  APPLE: 'APPLE',
  LINUX: 'LINUX',
};

export const roles = [
  {
    key: ROLE_KEYS.OWNER,
    name: '👑 Właściciel',
    color: 0xf1c40f,
    hoist: true,
    permissions: [PermissionFlagsBits.Administrator],
  },
  {
    key: ROLE_KEYS.ADMIN,
    name: '🛡️ Administrator',
    color: 0xe74c3c,
    hoist: true,
    permissions: [PermissionFlagsBits.Administrator],
  },
  {
    key: ROLE_KEYS.MODERATOR,
    name: '🔨 Moderator',
    color: 0xe67e22,
    hoist: true,
    permissions: [
      PermissionFlagsBits.ViewAuditLog,
      PermissionFlagsBits.KickMembers,
      PermissionFlagsBits.BanMembers,
      PermissionFlagsBits.ModerateMembers,
      PermissionFlagsBits.ManageMessages,
      PermissionFlagsBits.ManageThreads,
      PermissionFlagsBits.ManageNicknames,
      PermissionFlagsBits.MuteMembers,
      PermissionFlagsBits.DeafenMembers,
      PermissionFlagsBits.MoveMembers,
    ],
  },
  {
    key: ROLE_KEYS.SUPPORT,
    name: '🧰 Support',
    color: 0x2ecc71,
    hoist: true,
    permissions: [
      PermissionFlagsBits.ManageMessages,
      PermissionFlagsBits.ManageThreads,
      PermissionFlagsBits.ModerateMembers,
      PermissionFlagsBits.MoveMembers,
    ],
  },
  {
    key: ROLE_KEYS.CREATOR,
    name: '🧑‍💻 Twórca',
    color: 0x9b59b6,
    hoist: true,
    permissions: [],
  },
  {
    key: ROLE_KEYS.TESTER,
    name: '🧪 Tester',
    color: 0x1abc9c,
    hoist: true,
    permissions: [],
  },
  {
    key: ROLE_KEYS.VIP,
    name: '🌟 VIP',
    color: 0xff73fa,
    hoist: true,
    permissions: [],
  },
  {
    key: ROLE_KEYS.UNVERIFIED,
    name: 'Niezweryfikowany',
    color: 0x747f8d,
    hoist: false,
    permissions: [],
  },
  {
    key: ROLE_KEYS.MEMBER,
    name: 'Zweryfikowany',
    legacyNames: ['👤 Członek', '✅ Zweryfikowany'],
    color: 0x3498db,
    hoist: false,
    permissions: [],
  },
  {
    key: ROLE_KEYS.VERIFIED,
    name: 'Weryfikacja ukończona',
    color: 0x57f287,
    hoist: false,
    permissions: [],
  },
  {
    key: ROLE_KEYS.POLISH,
    name: '🇵🇱 Polski',
    color: 0xdc143c,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Polski / Polish',
    buttonEmoji: '🇵🇱',
  },
  {
    key: ROLE_KEYS.ENGLISH,
    name: '🇬🇧 English',
    color: 0x4169e1,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'English',
    buttonEmoji: '🇬🇧',
  },
  {
    key: ROLE_KEYS.NEWS,
    name: '📰 Aktualizacje',
    color: 0x5865f2,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Aktualizacje / Updates',
    buttonEmoji: '📰',
  },
  {
    key: ROLE_KEYS.EVENTS,
    name: '🎉 Eventy',
    color: 0xf39c12,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Eventy / Events',
    buttonEmoji: '🎉',
  },
  {
    key: ROLE_KEYS.GAMING,
    name: '🎮 Wspólna gra',
    color: 0x57f287,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Wspólna gra / Gaming',
    buttonEmoji: '🎮',
  },
  {
    key: ROLE_KEYS.PC,
    name: '🖥️ PC',
    color: 0x95a5a6,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'PC',
    buttonEmoji: '🖥️',
  },
  {
    key: ROLE_KEYS.ANDROID,
    name: '📱 Android',
    color: 0x3ddc84,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Android',
    buttonEmoji: '📱',
  },
  {
    key: ROLE_KEYS.APPLE,
    name: '🍎 Apple',
    color: 0xecf0f1,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Apple',
    buttonEmoji: '🍎',
  },
  {
    key: ROLE_KEYS.LINUX,
    name: '🐧 Linux',
    color: 0xf7df1e,
    hoist: false,
    permissions: [],
    selfAssignable: true,
    buttonLabel: 'Linux',
    buttonEmoji: '🐧',
  },
];

export const staffRoleKeys = [
  ROLE_KEYS.OWNER,
  ROLE_KEYS.ADMIN,
  ROLE_KEYS.MODERATOR,
  ROLE_KEYS.SUPPORT,
];

export const categories = [
  { key: 'START', name: '📌 START', permissionMode: 'MEMBER' },
  {
    key: 'COMMUNITY',
    name: '🌐 COMMUNITY',
    legacyNames: ['🌐 SPOŁECZNOŚĆ'],
    permissionMode: 'MEMBER',
  },
  {
    key: 'EMULATORS',
    name: '🕹️ EMULATORS',
    legacyNames: ['🕹️ EMULATORY'],
    permissionMode: 'MEMBER',
  },
  {
    key: 'SUPPORT',
    name: '🆘 SUPPORT',
    legacyNames: ['🆘 POMOC'],
    permissionMode: 'MEMBER',
  },
  {
    key: 'VOICE',
    name: '🎙️ VOICE CHANNELS',
    legacyNames: ['🎙️ KANAŁY GŁOSOWE'],
    permissionMode: 'MEMBER_VOICE',
  },
  {
    key: 'STAFF',
    name: '🛡️ STAFF AREA',
    legacyNames: ['🛡️ STREFA EKIPY'],
    permissionMode: 'STAFF',
  },
];

export const channels = [
  {
    key: 'VERIFICATION',
    category: 'START',
    name: 'verification',
    legacyNames: ['weryfikacja'],
    type: ChannelType.GuildText,
    topic: 'Zweryfikuj się, aby uzyskać dostęp / Verify to access the EMUPLCOOM server.',
    permissionMode: 'VERIFICATION',
    adoptExisting: true,
    preserveOverwrites: true,
  },
  {
    key: 'WELCOME',
    category: 'START',
    name: 'welcome',
    legacyNames: ['powitanie'],
    type: ChannelType.GuildText,
    topic: 'Witaj w społeczności GameLoop / Welcome to the GameLoop community.',
    permissionMode: 'MEMBER',
  },
  {
    key: 'GAMELOOP_INFO',
    category: 'START',
    name: 'gameloop-info',
    legacyNames: ['o-gameloop'],
    type: ChannelType.GuildText,
    topic:
      'Czym jest GameLoop, legalność, bezpieczeństwo i oficjalne linki / GameLoop explained, legality, safety and official links.',
    permissionMode: 'MEMBER',
    createIfMissing: true,
  },
  {
    key: 'RULES',
    category: 'START',
    name: 'rules',
    legacyNames: ['regulamin'],
    type: ChannelType.GuildText,
    topic: 'Zasady społeczności / EMUPLCOOM community rules.',
    permissionMode: 'MEMBER',
  },
  {
    key: 'ANNOUNCEMENTS',
    category: 'START',
    name: 'announcements',
    legacyNames: ['ogloszenia'],
    type: ChannelType.GuildText,
    acceptedTypes: [ChannelType.GuildAnnouncement],
    topic: 'Najważniejsze informacje / Important server news and updates.',
    permissionMode: 'MEMBER',
  },
  {
    key: 'ROLES',
    category: 'START',
    name: 'choose-roles',
    legacyNames: ['wybierz-role'],
    type: ChannelType.GuildText,
    topic: 'Wybierz swoje role / Choose your roles.',
    permissionMode: 'MEMBER',
  },
  {
    key: 'FAQ',
    category: 'START',
    name: 'faq',
    type: ChannelType.GuildText,
    topic: 'Najczęstsze pytania / Frequently asked questions.',
    permissionMode: 'MEMBER',
  },
  {
    key: 'GENERAL',
    category: 'COMMUNITY',
    name: 'general',
    legacyNames: ['ogolny'],
    type: ChannelType.GuildText,
    topic: 'Główny czat społeczności / Main EMUPLCOOM community chat.',
    slowmode: 2,
  },
  {
    key: 'CHAT_PL',
    category: 'COMMUNITY',
    name: 'polish-chat',
    legacyNames: ['chat-pl'],
    type: ChannelType.GuildText,
    topic: 'Główny czat w języku polskim / Main Polish-language chat. 🇵🇱',
    slowmode: 2,
    permissionMode: 'LANGUAGE_POLISH',
  },
  {
    key: 'CHAT_GB',
    category: 'COMMUNITY',
    name: 'english-chat',
    legacyNames: ['chat-gb'],
    type: ChannelType.GuildText,
    topic: 'Main community chat in English. 🇬🇧',
    slowmode: 2,
    permissionMode: 'LANGUAGE_ENGLISH',
  },
  {
    key: 'INTRODUCTIONS',
    category: 'COMMUNITY',
    name: 'introductions',
    legacyNames: ['przedstaw-sie'],
    type: ChannelType.GuildText,
    topic: 'Przedstaw się społeczności / Introduce yourself to the community.',
    slowmode: 10,
  },
  {
    key: 'SHOWCASE',
    category: 'COMMUNITY',
    name: 'setups-and-screenshots',
    legacyNames: ['screeny-i-setupy'],
    type: ChannelType.GuildText,
    topic: 'Pokaż swój sprzęt i ustawienia / Share your hardware and emulator setup.',
  },
  {
    key: 'MEMES',
    category: 'COMMUNITY',
    name: 'memes',
    legacyNames: ['memy'],
    type: ChannelType.GuildText,
    topic: 'Memy o grach i emulatorach / Gaming and emulator memes.',
  },
  {
    key: 'OFFTOPIC',
    category: 'COMMUNITY',
    name: 'off-topic',
    type: ChannelType.GuildText,
    topic: 'Luźne rozmowy / Conversations not directly related to emulators.',
  },
  {
    key: 'BOT_COMMANDS',
    category: 'COMMUNITY',
    name: 'bot-commands',
    legacyNames: ['komendy-bota'],
    type: ChannelType.GuildText,
    topic: 'Komendy botów / Use bot commands here.',
  },
  {
    key: 'EMU_NEWS',
    category: 'EMULATORS',
    name: 'emulator-news',
    legacyNames: ['aktualnosci-emulacji'],
    type: ChannelType.GuildText,
    topic: 'Aktualności emulatorów / Emulator releases, fixes and important news.',
  },
  {
    key: 'CONFIGS',
    category: 'EMULATORS',
    name: 'configurations',
    legacyNames: ['konfiguracje'],
    type: ChannelType.GuildText,
    topic: 'Sprawdzone ustawienia / Tested emulator and controller configurations.',
  },
  {
    key: 'COMPATIBILITY',
    category: 'EMULATORS',
    name: 'game-compatibility',
    legacyNames: ['kompatybilnosc-gier'],
    type: ChannelType.GuildText,
    topic: 'Zgodność i błędy gier / Game compatibility, tests and known issues.',
  },
  {
    key: 'PERFORMANCE',
    category: 'EMULATORS',
    name: 'performance-and-hardware',
    legacyNames: ['wydajnosc-i-sprzet'],
    type: ChannelType.GuildText,
    topic: 'Optymalizacja i sprzęt / Performance, requirements and hardware advice.',
  },
  {
    key: 'MODS',
    category: 'EMULATORS',
    name: 'mods-and-saves',
    legacyNames: ['mody-i-save'],
    type: ChannelType.GuildText,
    topic: 'Mody i zapisy / Mods, graphics improvements and save management.',
  },
  {
    key: 'RETRO',
    category: 'EMULATORS',
    name: 'retro-zone',
    legacyNames: ['retro-strefa'],
    type: ChannelType.GuildText,
    topic: 'Klasyczne gry i platformy / Classic games, platforms and emulation history.',
  },
  {
    key: 'HELP',
    category: 'SUPPORT',
    name: 'emulator-help',
    legacyNames: ['pomoc-emulatory'],
    type: ChannelType.GuildText,
    topic: 'Pomoc techniczna / Describe GameLoop, your system, hardware and exact issue.',
    slowmode: 10,
  },
  {
    key: 'ISSUES',
    category: 'SUPPORT',
    name: 'report-an-issue',
    legacyNames: ['zglos-problem'],
    type: ChannelType.GuildText,
    topic: 'Problemy z serwerem lub botem / Server or bot technical issues.',
    slowmode: 15,
  },
  {
    key: 'SUGGESTIONS',
    category: 'SUPPORT',
    name: 'suggestions',
    legacyNames: ['propozycje'],
    type: ChannelType.GuildText,
    topic: 'Propozycje rozwoju / Ideas for improving the EMUPLCOOM community.',
    slowmode: 30,
  },
  {
    key: 'LOBBY',
    category: 'VOICE',
    name: 'Lobby',
    type: ChannelType.GuildVoice,
  },
  {
    key: 'GAMING_VOICE',
    category: 'VOICE',
    name: 'Play Together',
    legacyNames: ['Wspólna gra'],
    type: ChannelType.GuildVoice,
  },
  {
    key: 'HELP_VOICE',
    category: 'VOICE',
    name: 'Voice Help',
    legacyNames: ['Pomoc głosowa'],
    type: ChannelType.GuildVoice,
    userLimit: 8,
  },
  {
    key: 'AFK',
    category: 'VOICE',
    name: 'AFK',
    type: ChannelType.GuildVoice,
  },
  {
    key: 'STAFF_CHAT',
    category: 'STAFF',
    name: 'staff-chat',
    legacyNames: ['ekipa-chat'],
    type: ChannelType.GuildText,
    topic: 'Prywatny kanał ekipy / Private EMUPLCOOM staff channel.',
    permissionMode: 'STAFF',
  },
  {
    key: 'REPORTS',
    category: 'STAFF',
    name: 'reports',
    legacyNames: ['zgloszenia'],
    type: ChannelType.GuildText,
    topic: 'Zgłoszenia i moderacja / Reports and moderation cases.',
    permissionMode: 'STAFF',
  },
  {
    key: 'LOGS',
    category: 'STAFF',
    name: 'bot-logs',
    legacyNames: ['logi-bota'],
    type: ChannelType.GuildText,
    topic: 'Logi bota / EMUPLCOOM bot configuration and activity logs.',
    permissionMode: 'STAFF',
  },
  {
    key: 'STAFF_VOICE',
    category: 'STAFF',
    name: 'Staff',
    legacyNames: ['Ekipa'],
    type: ChannelType.GuildVoice,
    permissionMode: 'STAFF_VOICE',
  },
];

export const selfAssignableRoles = roles.filter((role) => role.selfAssignable);
